import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'FinanceOS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=' min-h-screen text-white'>
      <main>{children}</main>
    </div>
  );
}
