import type { Metadata } from 'next';
import './globals.css';
import { IntroductionHeader } from '@/components/Introduction/header';

export const metadata: Metadata = {
  title: 'FinanceOS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br' className={`h-full`}>
      <body className='min-h-full flex flex-col bg-primary-black-introduction text-white overflow-x-hidden'>
        <IntroductionHeader />
        {children}
      </body>
    </html>
  );
}
