import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme/ThemeProvider';
import { JetBrains_Mono } from 'next/font/google';

const jetbrainsMono = JetBrains_Mono({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-dm-mono', // Mantém a mesma variável que você já configurou no CSS
});

export const metadata: Metadata = {
  title: 'FinanceOS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='pt-br'
      className={`h-full scroll-smooth ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      <body className={`min-h-full flex flex-col overflow-x-hidden `}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
